// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MyShop.Infrastructure.Models;

public partial class Price
{
    public int PriceId { get; set; }

    public int ProductId { get; set; }

    public decimal Amount { get; set; }

    public virtual Product Product { get; set; }
}