// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyShop.Infrastructure.Models;

public partial class Stock
{
    public int ProductId { get; set; }

    public int Quantity { get; set; }
}