// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace MyShop.Infrastructure.Models;

public partial class MyShopDbContext : DbContext
{
    public MyShopDbContext(DbContextOptions<MyShopDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Price> Prices { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Stock> Stocks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>().ToTable("product");
        modelBuilder.Entity<Price>().ToTable("price");
        modelBuilder.Entity<Stock>().ToTable("stock");
        modelBuilder.Entity<Product>()
            .HasKey(p => p.ProductId);

        modelBuilder.Entity<Product>()
            .HasOne(p => p.Price)
            .WithOne(pr => pr.Product)
            .HasForeignKey<Price>(pr => pr.ProductId);

        modelBuilder.Entity<Product>()
            .HasOne(p => p.Stock)
            .WithOne(s => s.Product)
            .HasForeignKey<Stock>(s => s.ProductId);

        modelBuilder.Entity<Price>()
            .HasKey(pr => pr.PriceId);

        modelBuilder.Entity<Stock>()
            .HasKey(s => s.StockId);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}